id: opecha:P008074
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20326
  title: གཉའ་ཁྲི་བཙན་པོ་ཞིབ་འཇུག
  volume:
    23e7d01377a141d9a4532fa5a29f22b4:
      image_group_id: I8LS20328
      title: Volume 1 of gnya' khri btsan po zhib 'jug
      volume_number: 1
      total_pages: 805
  author: ''
ebook_metadata:
  title: གཉའ་ཁྲི་བཙན་པོ་ཞིབ་འཇུག
  author: ''
  sku: P008074
  cover: cover.jpg
  layers:
  - pagination
