id: P008074
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20326
  title: གཉའ་ཁྲི་བཙན་པོ་ཞིབ་འཇུག
  author: ''
  volumes:
    eade7a0c9ded4138bd73f29dbdcfbee5:
      image_group_id: I8LS20328
      title: ''
      volume_number: 1
      total_pages: 805
ebook_metadata:
  title: གཉའ་ཁྲི་བཙན་པོ་ཞིབ་འཇུག
  author: ''
  sku: P008074
  cover: cover.jpg
  layers:
  - pagination
