id: IDE8B7E74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:38:43+00:00'
last_modified: '2022-06-08T18:14:39.180367+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20326
  title: གཉའ་ཁྲི་བཙན་པོ་ཞིབ་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    A9DF:
      image_group_id: I8LS20328
      title: Volume 1 of gnya' khri btsan po zhib 'jug
      total_pages: 805
      order: 1
      base_file: A9DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
